# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macOS-10.14'

steps:
#- task: InstallAppleCertificate@2
#  displayName: 'Install a development certificate'
#  inputs:
#    certSecureFile: '8c1a7484-f544-456b-b4a4-745606ab3ee4'
#    certPwd: '$(certificatePassword)'

- task: InstallAppleCertificate@2
  displayName: 'Install a distribution certificate'
  inputs:
    certSecureFile: 'ca90c5a9-bb59-4aee-91ee-f66484de377e'
    certPwd: '$(certificatePassword)'

#- task: InstallAppleProvisioningProfile@1
#  displayName: 'Install a development provisioning profile'
#  inputs:
#    provProfileSecureFile: 'f720023d-d237-4c73-8794-caaa5fdea9c8'

- task: InstallAppleProvisioningProfile@1
  displayName: 'Install a development provisioning profile'
  inputs:
    provProfileSecureFile: '5da5c23a-c984-45a6-af0f-4abf261ae0dc'


- task: Xcode@5
  displayName: 'Xcode test'
  inputs:
    actions: 'test'
    configuration: 'Debug'
    sdk: 'iphonesimulator'
    scheme: 'BeastMatchTests'
    destinationPlatformOption: 'iOS'
    publishJUnitResults: true

- task: Xcode@5
  displayName: 'Xcode build'
  inputs:
    scheme: 'BeastMatch'
    configuration: 'Release'
    sdk: 'iphoneos'
    packageApp: true
    signingOption: 'manual'
    provisioningProfileUuid: '66ea39f2-6cdf-4163-8029-f1137cbdac73'


#- task: CopyFiles@2
#  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
#  inputs:
#    SourceFolder: '$(system.defaultworkingdirectory)'
#    Contents: '**/*.ipa'
#    TargetFolder: '$(build.artifactstagingdirectory)'
#  condition: succeededOrFailed()
#
#- task: PublishBuildArtifacts@1
#  displayName: 'Publish Artifact: drop'
#  inputs:
#    PathtoPublish: '$(build.artifactstagingdirectory)'
#  condition: succeededOrFailed()
#
#- task: AppCenterTest@1
#  displayName: 'Test with Visual Studio App Center'
#  inputs:
#    appFile: '**/*.ipa'
#  enabled: false
#  condition: succeededOrFailed()
#
#- task: AppCenterDistribute@2
#  displayName: 'Deploy **/*.ipa to Visual Studio App Center'
#  inputs:
#    appFile: '**/*.ipa'
#    symbolsIncludeParentDirectory: false
#  enabled: false
#  condition: succeededOrFailed()


