# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: InstallAppleCertificate@2
  displayName: 'Install an Apple certificate'
  inputs:
    certSecureFile: 'ios_dist_2.p12'
    certPwd: '$(certificatePassword)'

- task: InstallAppleProvisioningProfile@1
  displayName: 'Install an Apple provisioning profile'
  inputs:
    provProfileSecureFile: 'App_Store_Distribution.mobileprovision'

- task: Xcode@5
  displayName: 'Test'
  inputs:
    actions: 'test'
    configuration: 'Debug'
    sdk: 'iphonesimulator'
    scheme: 'BeastMatchTests'
    destinationPlatformOption: 'iOS'
    publishJUnitResults: true

- task: Xcode@5
  displayName: 'Release Build'
  inputs:
    scheme: 'BeastMatch'
    configuration: 'Release'
    sdk: 'iphoneos'
    packageApp: true
    signingOption: 'manual'
    provisioningProfileUuid: '66ea39f2-6cdf-4163-8029-f1137cbdac73'
